ALTER TABLE user_roles ADD COLUMN user_only BOOLEAN NOT NULL DEFAULT 0;
ALTER TABLE user_roles ADD COLUMN ou_inherit_allowed BOOLEAN NOT NULL DEFAULT 0;
ALTER TABLE rolegroup ADD COLUMN user_only BOOLEAN NOT NULL DEFAULT 0;
ALTER TABLE rolegroup ADD COLUMN ou_inherit_allowed BOOLEAN NOT NULL DEFAULT 0;