CREATE TABLE req_org_unit_user_role_cache (
   id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
   ou_uuid VARCHAR(36) NULL,
   user_role_id BIGINT NULL,
   CONSTRAINT FK_REQ_ORG_UNIT_USER_ROLE_CACHE_ON_OU_UUID FOREIGN KEY (ou_uuid) REFERENCES ous (uuid) ON DELETE CASCADE,
   CONSTRAINT FK_REQ_ORG_UNIT_USER_ROLE_CACHE_ON_USER_ROLE FOREIGN KEY (user_role_id) REFERENCES user_roles (id) ON DELETE CASCADE
);

CREATE TABLE req_org_unit_role_group_cache (
   id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
   ou_uuid VARCHAR(36) NULL,
   role_group_id BIGINT NULL,
   CONSTRAINT FK_REQ_ORG_UNIT_ROLE_GROUP_CACHE_ON_OU_UUID FOREIGN KEY (ou_uuid) REFERENCES ous (uuid) ON DELETE CASCADE,
   CONSTRAINT FK_REQ_ORG_UNIT_ROLE_GROUP_CACHE_ON_ROLE_GROUP FOREIGN KEY (role_group_id) REFERENCES rolegroup (id) ON DELETE CASCADE
);