ALTER TABLE ou_roles ADD COLUMN inherit BOOLEAN NOT NULL DEFAULT 0;
ALTER TABLE ou_rolegroups ADD COLUMN inherit BOOLEAN NOT NULL DEFAULT 0;
ALTER TABLE ou_roles ADD COLUMN id BIGINT PRIMARY KEY AUTO_INCREMENT;
ALTER TABLE ou_rolegroups ADD COLUMN id BIGINT PRIMARY KEY AUTO_INCREMENT;
