ALTER TABLE user_roles_mapping 
ADD COLUMN start_date DATE NULL,
ADD COLUMN stop_date DATE NULL,
ADD COLUMN inactive BOOLEAN NOT NULL DEFAULT 0;

ALTER TABLE user_rolegroups 
ADD COLUMN start_date DATE NULL,
ADD COLUMN stop_date DATE NULL,
ADD COLUMN inactive BOOLEAN NOT NULL DEFAULT 0;

ALTER TABLE title_roles 
ADD COLUMN start_date DATE NULL,
ADD COLUMN stop_date DATE NULL,
ADD COLUMN inactive BOOLEAN NOT NULL DEFAULT 0;

ALTER TABLE title_rolegroups 
ADD COLUMN start_date DATE NULL,
ADD COLUMN stop_date DATE NULL,
ADD COLUMN inactive BOOLEAN NOT NULL DEFAULT 0;

ALTER TABLE ou_roles 
ADD COLUMN start_date DATE NULL,
ADD COLUMN stop_date DATE NULL,
ADD COLUMN inactive BOOLEAN NOT NULL DEFAULT 0;

ALTER TABLE ou_rolegroups 
ADD COLUMN start_date DATE NULL,
ADD COLUMN stop_date DATE NULL,
ADD COLUMN inactive BOOLEAN NOT NULL DEFAULT 0;

ALTER TABLE position_roles 
ADD COLUMN start_date DATE NULL,
ADD COLUMN stop_date DATE NULL,
ADD COLUMN inactive BOOLEAN NOT NULL DEFAULT 0;

ALTER TABLE position_rolegroups 
ADD COLUMN start_date DATE NULL,
ADD COLUMN stop_date DATE NULL,
ADD COLUMN inactive BOOLEAN NOT NULL DEFAULT 0;
