version: '3.3'
services:
  db:
    image: mariadb:10.11
    environment:
      MARIADB_DATABASE: 'rc'
      MARIADB_ROOT_PASSWORD: 'Test1234'

    ports:
      - "3306:3306"
    expose:
      - '3306'

