version: '3.3'
services:
  db:
    image: mariadb:10.6.14
    environment:
      MARIADB_DATABASE: 'rc'
      MARIADB_ROOT_PASSWORD: 'Test1234'

    ports:
      - "3306:3306"
    expose:
      - '3306'
    volumes:
      - rollekatalog-db:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
volumes:
  rollekatalog-db:
