ALTER TABLE constraint_type_value_sets ADD id BIGINT NOT NULL PRIMARY KEY IDENTITY(1, 1);
ALTER TABLE ous_itsystems ADD id BIGINT NOT NULL PRIMARY KEY IDENTITY(1, 1);
ALTER TABLE report_template_user ADD id BIGINT NOT NULL PRIMARY KEY IDENTITY(1, 1);
ALTER TABLE system_role_supported_constraints ADD id BIGINT NOT NULL PRIMARY KEY IDENTITY(1, 1);
ALTER TABLE title_rolegroups_ous ADD id BIGINT NOT NULL PRIMARY KEY IDENTITY(1, 1);
ALTER TABLE title_roles_ous ADD id BIGINT NOT NULL PRIMARY KEY IDENTITY(1, 1);
