package dk.digitalidentity.rc.controller.api.model;

public enum ConstraintValueTypeAM {
	LEVEL_1, LEVEL_2, LEVEL_3, LEVEL_4, LEVEL_5, LEVEL_6,

	INHERITED_FROM_MANAGER_ROLE,
	EXTENDED_INHERITED_FROM_MANAGER_ROLE,
	INHERITED_FROM_FUNCTIONS,
	EXTENDED_INHERITED_FROM_FUNCTIONS,
	INHERITED,
	SELECTED_INHERITED,
	EXTENDED_INHERITED,
	READ_AND_WRITE,
	VALUE,
	POSTPONED;
}
